# Codecov configuration for PubSub-Go Library
# Documentation: https://docs.codecov.com/docs/codecovyml-reference
# Validator: https://api.codecov.io/validate

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 90%           # High coverage target (current: 95.9%)
        threshold: 2%         # Allow 2% drop from target
        base: auto
        informational: false  # Fail if below target
        only_pulls: false

    patch:
      default:
        target: auto          # Auto-detect reasonable target for changes
        threshold: 10%        # Allow 10% variance for patches
        base: auto
        informational: true   # Don't fail PRs, just inform
        only_pulls: false

  ignore:
    - "cmd/**"                # CLI tools and standalone server
    - "examples/**"           # Example code (not covered by tests)
    - "internal/deprecated/**" # Deprecated legacy code
    - "testdata/**"           # Test data files
    - "**/*_test.go"          # Test files themselves
    - "tmp/**"                # Temporary files
    - "migrations/**"         # SQL migration files

comment:
  layout: "header, diff, flags, files, footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

# GitHub integration
github_checks:
  annotations: true
